// android/build.gradle

import java.nio.file.Files
import java.nio.file.Paths
import java.nio.charset.StandardCharsets
import java.util.regex.Pattern
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

buildscript {
  ext {
    buildToolsVersion = "35.0.0"
    compileSdkVersion = 35
    targetSdkVersion = 35
    minSdkVersion = 26

    ndkVersion = "26.1.10909125"

    versionCode = 1
    versionName = "1.0.1"

    def changeLogFile = file("../changelog.md")
    def charset = StandardCharsets.UTF_8
    def content = new String(Files.readAllBytes(Paths.get(changeLogFile.path)), charset)

    def versionCodePattern = Pattern.compile('## versionCode = (\\d+)')
    def matcher = versionCodePattern.matcher(content)
    def newContent = content
    def maxVersionCode = 0

    while (matcher.find()) {
      def v = matcher.group(1).toInteger()
      if (v > maxVersionCode) {
        maxVersionCode = v
      }
    }

    rootProject.ext.versionCode = maxVersionCode + 1
    if (rootProject.ext.versionCode >= 100) {
      def firstStr = rootProject.ext.versionCode.toString().substring(0, 1)
      def remainStr = rootProject.ext.versionCode.toString().substring(1)
      rootProject.ext.versionName = "1." + firstStr + "." + remainStr
    } else {
      rootProject.ext.versionName = "1.0." + rootProject.ext.versionCode
    }

    def now = LocalDateTime.now()
    def formatter = DateTimeFormatter.ofPattern('yyyy-MM-dd (HH:mm:ss)')
    def timestamp = now.format(formatter)

    def newVersionSection = "\n## versionCode = " + rootProject.ext.versionCode + "\n\n- " + "versionName = " + rootProject.ext.versionName + "\n- " + timestamp + "\n"
    newContent = newContent + newVersionSection

    Files.write(Paths.get(changeLogFile.path), newContent.getBytes(charset))
    println "Version code has been incremented to " + rootProject.ext.versionCode + " and new version section added."
  }
}
